os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9
cache:
  directories:
  - ${BUNDLE_PATH:-vendor/bundle}

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
    elif [ $TRAVIS_OS_NAME == "osx" ]; then
      rvm use 2.4.2 --install --binary --fuzzy;
      ruby --version;
      gem install bundler;
      bundle --version;
      brew update;
      brew outdated swiftlint || brew upgrade swiftlint;
    fi

install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle};
    fi

script:
  - swift --version
  - swift build
  - swift build -c release
  - swift test
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      swiftlint;
      bundle exec pod lib lint;
    fi

before_deploy:
  - bundle exec github_changelog_generator -t ${DANGER_GITHUB_API_TOKEN} --between-tags ${TRAVIS_TAG}

deploy:
  - provider: script
    skip_cleanup: true
    script: rvm 2.4.2 do bundle exec ./Scripts/github_release.rb -s ${DANGER_GITHUB_API_TOKEN} -r asensei/Result -c CHANGELOG.md -t ${TRAVIS_TAG}
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx

notifications:
  email:
    on_success: never
    on_failure: change
